/// Vocabulário pt-BR embarcado para atalhos de categorização.
///
/// Diferente de uma regra, uma entrada aqui nunca categoriza silenciosamente: ela apenas ajuda a
/// ordenar até três escolhas plausíveis para o usuário. As frases mais específicas vêm antes das
/// genéricas para que, por exemplo, "MERCADO LIVRE" seja tratado como compra antes de "MERCADO".
///
/// A curadoria foi ampliada em julho de 2026 a partir de referências públicas setoriais (IRTT Top
/// 300, Ranking ABRAS, Ranking ABF de franquias, Kantar QSR e Fecombustíveis). Permanecem marcas
/// com presença real no Brasil e termos de gênero úteis em descrições bancárias. Este arquivo é a
/// cópia embarcada versionada; não há consulta de rede durante a importação.
#[derive(Debug, Clone, Copy)]
pub struct VocabularyEntry {
    pub category_id: &'static str,
    pub phrases: &'static [&'static str],
}

/// Versão do conteúdo embarcado. Incrementar sempre que termos forem adicionados, removidos ou
/// tiverem sua categoria alterada, para que mudanças de ranking sejam rastreáveis em testes e
/// notas de versão sem persistir configuração nova no banco.
pub const PT_BR_CATEGORY_VOCABULARY_VERSION: u32 = 5;
const _: () = assert!(PT_BR_CATEGORY_VOCABULARY_VERSION > 0);

pub const PT_BR_CATEGORY_VOCABULARY: &[VocabularyEntry] = &[
    VocabularyEntry {
        category_id: "subscriptions",
        phrases: &[
            "NETFLIX",
            "SPOTIFY",
            "PRIME VIDEO",
            "SUBSCRIPTION",
            "AMAZON PRIME",
            "DISNEY PLUS",
            "GLOBOPLAY",
            "HBO MAX",
            "YOUTUBE PREMIUM",
            "APPLE MUSIC",
            "DEEZER",
            "PARAMOUNT PLUS",
            "CRUNCHYROLL",
            "MUBI",
            "ADOBE CREATIVE CLOUD",
            "MICROSOFT 365",
            "CANVA PRO",
            "APPLE ONE",
            "APPLE TV PLUS",
            "DISNEY PLUS HOTSTAR",
            "STAR PLUS",
            "MAX STREAMING",
            "TELECINE",
            "LOOKE",
            "OLD FLIX",
            "PLUTO TV",
            "TUBI TV",
            "DAZN",
            "PREMIERE",
            "ESPN",
            "PARAMOUNT",
            "GLOBOPLAY PREMIERE",
            "VIVO PLAY",
            "CLARO TV MAIS",
            "ANTHROPIC",
            "CLARO VIDEO",
            "SKY PLAY",
            "MELI PLUS",
            "MERCADO PLAY",
            "AMAZON MUSIC",
            "AMAZON PRIME GAMING",
            "YOUTUBE MUSIC",
            "YOUTUBE TV",
            "TIDAL",
            "AUDIBLE",
            "KINDLE UNLIMITED",
            "GOOGLE ONE",
            "GOOGLE WORKSPACE",
            "ICLOUD",
            "DROPBOX PLUS",
            "ONEDRIVE",
            "NOTION PLUS",
            "EVERNOTE",
            "TODOIST",
            "NORDVPN",
            "EXPRESSVPN",
            "SURFSHARK",
            "DUOLINGO PLUS",
            "STRAVA",
            "FITBIT PREMIUM",
            "HEADSPACE",
            "CALM APP",
            "LIFE360",
            "ZOOM PRO",
            "SLACK PRO",
            "CHATGPT PLUS",
            "CLAUDE PRO",
            "GITHUB COPILOT",
            "AWS",
            "MICROSOFT AZURE",
            "GOOGLE CLOUD",
            "DIGITALOCEAN",
            "HOSTINGER",
            "GODADDY",
            "WIX",
            "SHOPIFY",
            "RD STATION",
            "ROCK CONTENT",
            "JUSBRASIL PRO",
            "FOLHA DIGITAL",
            "GLOBO MAIS",
            "NEXO JORNAL",
            "VALOR ECONOMICO",
            "ESTADAO",
            "VEJA ASSINATURA",
            "SUPER INTERESSANTE",
            "REVISTA EXAME",
            "MEDIUM",
            "SUBSTACK",
            "PATREON",
            "ONLYFANS",
            "PORTA DOS FUNDOS",
            "ASSINATURA DIGITAL",
            "SERVICO DE STREAMING",
            "PLANO MENSAL DIGITAL",
        ],
    },
    VocabularyEntry {
        category_id: "shopping",
        phrases: &[
            "MERCADO LIVRE",
            "MERCADOLIVRE",
            "AMAZON",
            "SHOPEE",
            "SHEIN",
            "MAGAZINE LUIZA",
            "MAGALU",
            "CASAS BAHIA",
            "PONTO FRIO",
            "HAVAN",
            "LOJAS RENNER",
            "LOJAS RIACHUELO",
            "DECATHLON",
            "CENTAURO",
            "KABUM",
            "ALIEXPRESS",
            "MADEIRA MADEIRA",
            "CAMICADO",
            "ZATTINI",
            "NETSHOES",
            "TIKTOK SHOP",
            "OLX",
            "ENJOEI",
            "TEMU",
            "SHOPEE MALL",
            "AMERICANAS",
            "SUBMARINO",
            "SHOPTIME",
            "EXTRA",
            "CARREFOUR ECOMMERCE",
            "PERNAMBUCANAS",
            "LE BISCUIT",
            "RIACHUELO",
            "C A",
            "MARISA",
            "RENNER",
            "YOUCOM",
            "CAMBUCI",
            "HERING",
            "HERING KIDS",
            "FARM",
            "ANIMALE",
            "LE LIS",
            "AMARO",
            "ZARA",
            "GUESS",
            "LEVIS",
            "LACOSTE",
            "NIKE",
            "ADIDAS",
            "PUMA",
            "ASICS",
            "NEW BALANCE",
            "OLYMPIKUS",
            "FILA",
            "MIZUNO",
            "UNDER ARMOUR",
            "NIKE STORE",
            "AREZZO",
            "SCHUTZ",
            "VIA UNO",
            "SANTA LOLLA",
            "VIVARA",
            "MORANA",
            "MONTE CARLO JOIAS",
            "RI HAPPY",
            "PBKIDS",
            "LIVRARIA LEITURA",
            "LIVRARIA CULTURA",
            "FAST SHOP",
            "PONTO",
            "POLISHOP",
            "MULTILASER",
            "POSITIVO",
            "LENOVO",
            "DELL",
            "HP STORE",
            "SAMSUNG STORE",
            "APPLE STORE",
            "MOTOROLA",
            "XIAOMI",
            "ASUS",
            "AOC",
            "LG STORE",
            "KALUNGA",
            "LEITURA",
            "PETZ",
            "COBASI",
            "PETLOVE",
            "MUNDO PET",
            "BAGAGGIO",
            "LE POSTICHE",
            "MOBLY",
            "WESTWING",
            "MADEIRA MADEIRA SHOP",
            "SHOPEE EXPRESS",
            "MERCADO LIVRE FULL",
            "MERCADO LIVRE CLASSIFICADOS",
            "ALIEXPRESS BRASIL",
            "LOJAS TORRA",
            "LOJAS CEM",
            "GAZIN",
            "BEMOL",
            "LOJA DE DEPARTAMENTO",
            "LOJA DE ROUPAS",
            "LOJA DE CALCADOS",
            "LOJA DE ELETRONICOS",
            "LOJA ONLINE",
            "MARKETPLACE",
        ],
    },
    VocabularyEntry {
        category_id: "groceries",
        phrases: &[
            "SUPERMERCADO",
            "ATACADAO",
            "ATACADISTA",
            "MERCEARIA",
            "HORTIFRUTI",
            "SACOLAO",
            "CARREFOUR",
            "PAO DE ACUCAR",
            "ASSAI ATACADISTA",
            "GRUPO MATEUS",
            "SUPERMERCADOS BH",
            "SUPERMERCADO BH",
            "SUPERMERCADO MUFFATO",
            "SUPER MUFFATO",
            "SUPERMERCADO ANGELONI",
            "SUPERMERCADO CONDOR",
            "SUPERMERCADO ZAITER",
            "SAVEGNAGO",
            "SONDA SUPERMERCADOS",
            "COOP SUPERMERCADO",
            "TENDA ATACADO",
            "ROLDAO ATACADISTA",
            "ROLDAO",
            "SAM S CLUB",
            "SAMS CLUB",
            "HIROTA FOOD",
            "OBA HORTIFRUTI",
            "EXTRA HIPER",
            "EXTRA MERCADO",
            "NACIONAL SUPERMERCADO",
            "ZONA SUL",
            "HORTIFRUTI NATURAL DA TERRA",
            "ST MARCHE",
            "EMPORIO SANTA MARIA",
            "OBRA HORTIFRUTI",
            "MAMBO",
            "MAMBO HORTIFRUTI",
            "ZONA SUL SUPERMERCADO",
            "HIROTA",
            "VIOLETA",
            "VIOLETA SUPERMERCADOS",
            "NAGUMO",
            "FESTVAL",
            "CONDOR",
            "MUFFATO",
            "MUFFATO GO",
            "MART MINAS",
            "SUPER NOSSO",
            "VERDEMAR",
            "EPA",
            "SUPER ABC",
            "BRETAS",
            "BH MAIS",
            "BH ATACAREJO",
            "NOVO ATACAREJO",
            "ATACAREJO",
            "ATACAKAREJO",
            "DIA A DIA",
            "DIA A DIA ATACADISTA",
            "KOMPRAO",
            "KOMPRAO KOCH",
            "KOCH ATACADISTA",
            "KOCH HIPER",
            "GIASSI",
            "ANGELONI",
            "BISTEK",
            "IMPERATRIZ",
            "GIASSI SUPERMERCADOS",
            "HIPER IDEAL",
            "IDEAL SUPERMERCADOS",
            "MERCADINHO SAO LUIZ",
            "MERCANTIL RODRIGUES",
            "MERCANTIL NOVA ERA",
            "SUPER BOM",
            "SUPER ADEGA",
            "SUPER ADEGA ATACADISTA",
            "REDE SUPER",
            "REDE SUPERMARKET",
            "PREZUNIC",
            "GUANABARA",
            "MUNDIAL",
            "MUNDIAL SUPERMERCADOS",
            "INTER SUPERMERCADOS",
            "HORTAMIX",
            "SAVEGNAGO SUPERMERCADOS",
            "SONDA",
            "SACOLAO SAO JORGE",
            "SACOLAO HORTIFRUTI",
            "VERDURAO",
            "MERCADINHO",
            "EMPORIO",
            "CASA SANTA LUZIA",
            "EMPORIO BEM VIVER",
            "CASA DO SABAO",
            "SUPERMERCADO TATICO",
            "TAUSTE",
            "BARBOSA SUPERMERCADOS",
            "REDE SAVEGNAGO",
            "SUPERVIZA",
            "SUPERMERCADO ZEFERINO",
            "SUPERMERCADO DELTA MAX",
            "SUPERMERCADOS NORDESTAO",
            "SPANI ATACADISTA",
            "ROYAL SUPERMERCADOS",
            "SUPER PRIX",
            "PRECO BAIXO",
            "SUPER LAR",
            "SUPER LAR ATACADISTA",
            "ATACADAO DIA A DIA",
            "SUPER KOCH",
            "HIPER CARREFOUR",
            "CARREFOUR EXPRESS",
            "PAO DE ACUCAR MINUTO",
            "PAO DE ACUCAR GO",
            "ASSAI EXPANSAO",
            "MATEUS SUPERMERCADOS",
            "MIX MATEUS",
            "GRUPO PEREIRA",
            "PLURIX",
            "ZAFFARI",
            "COMERCIAL ZAFFARI",
            "BOURBON SUPERMERCADOS",
            "G BARBOSA",
            "PERINI",
            "FORT ATACADISTA",
            "COMPER",
            "LIDER SUPERMERCADOS",
            "ATAKAREJO",
            "VILLEFORT",
            "COSTA ATACADAO",
            "SUPERMERCADO BAHAMAS",
            "LOPES SUPERMERCADOS",
            "COVABRA",
            "JACOMAR",
            "TONIN SUPERMERCADOS",
            "HIPERMERCADO",
            "ATACADO DE ALIMENTOS",
            "MERCADO DE BAIRRO",
        ],
    },
    VocabularyEntry {
        category_id: "restaurants",
        phrases: &[
            "RESTAURANTE",
            "LANCHONETE",
            "PADARIA",
            "PANIFICADORA",
            "IFOOD",
            "RAPPI",
            "AIQFOME",
            "ZE DELIVERY",
            "MCDONALDS",
            "MC DONALDS",
            "BURGER KING",
            "OUTBACK",
            "GIRAFFAS",
            "HABIBS",
            "SPOLETO",
            "COCO BAMBU",
            "MADERO",
            "STARBUCKS",
            "CACAU SHOW",
            "KOPENHAGEN",
            "PIZZARIA",
            "HAMBURGUERIA",
            "SORVETERIA",
            "SUBWAY",
            "KFC",
            "POPEYES",
            "TACO BELL",
            "DOMINOS",
            "PIZZA HUT",
            "PIZZA PRIME",
            "PIZZA CREMOSA",
            "BEBU",
            "BOBS",
            "JERONIMO BURGER",
            "MINEIRO DELIVERY",
            "MOOCA PIZZA",
            "BURGER JOINT",
            "ZAMP",
            "THE FIFTIES",
            "JOHNNY ROCKETS",
            "PATTIES BURGER",
            "MADERO STEAK HOUSE",
            "JERONIMO",
            "PARRILLA",
            "FOGO DE CHAO",
            "NB STEAK",
            "RANCHO 53",
            "CAMARADA CAMARAO",
            "VIVENDA DO CAMARAO",
            "CAMARAO E CIA",
            "MARIA BRIGADEIRO",
            "BRIGADERIA",
            "BENDITO CACAU",
            "CACAU SHOW LOJA",
            "KOPENHAGEN CHOCOLATES",
            "BRASIL CACAU",
            "HAVANNA",
            "CASA BAUDUCCO",
            "BAUDUCCO",
            "CASA DO PAO DE QUEIJO",
            "REI DO MATE",
            "THE COFFEE",
            "CHEIRIN BAO",
            "GO COFFEE",
            "B LEM",
            "FRUTARIA",
            "SUCOS BAGACO",
            "NATURAL DA TERRA CAFE",
            "CAFE SUPLICY",
            "COFFEE LAB",
            "BREADS",
            "OFNER",
            "CONFEITARIA COLOMBO",
            "CASA DO PAO",
            "LA GUAPA",
            "APPLEBEES",
            "HARD ROCK CAFE",
            "SPETTUS",
            "BOTECO",
            "BAR DO ALEMAO",
            "MADERO CAFE",
            "FAMILIA MANOEL",
            "RESTAURANTE MANGAI",
            "FASANO RESTAURANTE",
            "DELIVERY MUCH",
            "99 FOOD",
            "UBER EATS",
            "KEETA",
            "CORNERSHOP",
            "JAMES DELIVERY",
            "RAPPI TURBO",
            "IFOOD MARKET",
            "IFOOD SHOP",
            "AIQFOME DELIVERY",
            "MARMITEX",
            "SALGADERIA",
            "ACAI",
            "ACAI FORMOSA",
            "OAKBERRY",
            "TROPICAL ACAI",
            "GRAO ESPRESSO",
            "BOALI",
            "FIT FOOD",
            "SPOLETO RESTAURANTE",
            "GRILETTO",
            "DIVINO FOGAO",
            "IFD",
            "CHINA IN BOX",
            "RAGAZZO",
            "CABANA BURGER",
            "MONTANA GRILL",
            "MANIA DE CHURRASCO",
            "PATRONI PIZZA",
            "CHIQUINHO SORVETES",
            "OGGI SORVETES",
            "THE BEST ACAI",
            "MILKY MOO",
            "CASA DE BOLOS",
            "CAFETERIA",
            "CHURRASCARIA",
            "DOCERIA",
            "CONFEITARIA",
            "PASTELARIA",
            "FAST FOOD",
            "FOOD SERVICE",
        ],
    },
    VocabularyEntry {
        category_id: "fuel",
        phrases: &[
            "POSTO DE COMBUSTIVEL",
            "POSTO COMBUSTIVEL",
            "AUTO POSTO",
            "POSTO SHELL",
            "POSTO IPIRANGA",
            "POSTO PETROBRAS",
            "POSTO BR",
            "SHELL BOX",
            "ABASTECIMENTO",
            "COMBUSTIVEL",
            "GASOLINA",
            "ETANOL",
            "GNV VEICULAR",
            "VIBRA ENERGIA",
            "ALE COMBUSTIVEIS",
            "RAIZEN",
            "IPIRANGA",
            "BR DISTRIBUIDORA",
            "PETROBRAS DISTRIBUIDORA",
            "REDE SIM",
            "REDE HG",
            "REDE OXXO POSTO",
            "ATEM",
            "ALESAT",
            "CIAPETRO",
            "SETTA COMBUSTIVEIS",
            "ROYAL FIC",
            "SP COMBUSTIVEIS",
            "PETRONAS",
            "ALE",
            "TEXACO",
            "AMPM",
            "BR MANIA",
            "SELECT SHELL",
            "POSTO RODOIL",
            "POSTO GRAAL",
            "POSTO TREVAO",
            "POSTO 3 IRMAOS",
            "POSTO GAVIAO",
            "POSTO PETROBRASIL",
            "POSTO SETE",
            "POSTO VIA BRASIL",
            "POSTO BANDEIRANTES",
            "POSTO PARADA",
            "POSTO RODOCENTER",
            "POSTO G10",
            "POSTO ALVORADA",
            "POSTO ITALIA",
            "POSTO IPIRANGA AMPM",
            "POSTO SHELL SELECT",
            "POSTO BR MANIA",
            "POSTO ALE",
            "POSTO RUFF",
            "POSTO PETROBRAS BR",
            "POSTO VIBRA",
            "POSTO RAIZEN",
            "POSTO ECO",
            "POSTO ECOBRASIL",
            "POSTO RODOSERV",
            "POSTO COMETA",
            "POSTO GRAAL PETROBRAS",
            "POSTO CAMINHONEIRO",
            "LAVAGEM AUTOMOTIVA",
            "LAVA JATO",
            "TROCA DE OLEO",
            "LUBRIFICANTE AUTOMOTIVO",
            "ABASTECE AI",
            "APP SHELL BOX",
            "APP PREMMIA",
            "PREMMIA",
            "KM DE VANTAGENS",
            "CLUBE EXTRA ABASTECIMENTO",
            "POSTO SIM",
            "POSTO STANG",
            "POSTO PETRONAS",
            "POSTO TEXACO",
            "POSTO LARCO",
            "POSTO VIAOESTE",
            "POSTO DOM PEDRO",
            "POSTO FERNANDAO",
            "POSTO JARDIM",
            "POSTO BRASILIA",
            "POSTO PLANALTO",
            "POSTO CENTRAL",
            "POSTO CAMPEAO",
            "POSTO NOVO HORIZONTE",
            "POSTO REAL",
            "POSTO RIO BRANCO",
            "POSTO FENIX",
            "POSTO TREVO",
            "POSTO JK",
            "POSTO PRESIDENTE",
            "POSTO OURO VERDE",
            "POSTO BOA VISTA",
            "POSTO SAO JOAO",
            "POSTO SANTA HELENA",
            "POSTO BOM RETIRO",
            "POSTO",
            "REDE DE POSTOS",
            "DISTRIBUIDORA DE COMBUSTIVEIS",
        ],
    },
    VocabularyEntry {
        category_id: "public-transport",
        phrases: &[
            "BILHETE UNICO",
            "CARTAO BOM",
            "CARTAO TOP",
            "TOP TRANSPORTE",
            "SPTRANS",
            "CPTM",
            "METRO SP",
            "METRORIO",
            "METRO RIO",
            "EMTU",
            "URBS CURITIBA",
            "RIOCARD",
            "GVBUS",
            "VEM RECIFE",
            "ONIBUS URBANO",
            "PASSAGEM DE ONIBUS",
            "MOBILIDADE RECIFE",
            "METRO BH",
            "METRO DF",
            "METROFOR",
            "METRO SALVADOR",
            "METRO BRASILIA",
            "TRENSURB",
            "VLT CARIOCA",
            "VLT SANTOS",
            "VLT RECIFE",
            "BHTRANS",
            "SPTRANS BILHETE",
            "CARTAO GIRO",
            "CARTAO LEVA",
            "CARTAO PASSE FACIL",
            "CARTAO PASSA FACIL",
            "CARTAO METROCARD",
            "METROCARD",
            "PASSE LIVRE",
            "PASSE ESCOLAR",
            "RECARGA CARTAO TRANSPORTE",
            "RECARGA RIOCARD",
            "RECARGA TOP",
            "RECARGA VEM",
            "RECARGA BOM",
            "RECARGA GIRO",
            "RECARGA LEVA",
            "RECARGA METROCARD",
            "COMPANHIA PAULISTA DE TRENS",
            "COMPANHIA DO METROPOLITANO",
            "CCR METRO",
            "MOBI RIO",
            "MOBI RECIFE",
            "MOVE BH",
            "MOBI CURITIBA",
            "TRANSURC",
            "TRANSCOL",
            "TRANSERP",
            "TRANSALVADOR",
            "CARRIS",
            "VIAQUATRO",
            "VIAMOBILIDADE",
            "MOBILIDADE SAMPA",
            "METRO RIO OPERACAO",
            "SUPERVIA",
            "URBS CARTAO",
            "TRANSCURITIBA",
            "TOP MOBILIDADE",
            "MOOVIT",
            "RECARGA ONIBUS",
            "RECARGA METRO",
            "TAXI COMUM",
            "TAXI SP",
            "TAXI RIO",
            "COOPER TAXI",
            "RADIO TAXI",
            "ONIBUS INTERMUNICIPAL",
            "ONIBUS RODOVIARIO",
            "PASSAGEM RODOVIARIA",
            "GUICHE RODOVIARIO",
            "COMETA ONIBUS",
            "ITAPEMIRIM",
            "GONTIJO",
            "UTIL",
            "1001 ONIBUS",
            "CATARINENSE",
            "EXPRESSO GUANABARA",
            "ANDORINHA",
            "VIACAO COMETA",
            "VIACAO GARCIA",
            "EUCATUR",
            "VIACAO UTIL",
            "BUSER",
            "DEONIBUS",
            "CLICKBUS",
            "QUERO PASSAGEM",
            "METROREC",
            "METRO BAHIA",
            "CARTAO SALVADOR",
            "ONIBUS COMETA",
            "PASSAGEM FERROVIARIA",
            "TREM INTERCIDADES",
            "BRT RIO",
            "BRT BRASILIA",
            "BRT CURITIBA",
            "ONIBUS",
            "METRO",
            "TREM",
            "VLT",
            "RECARGA TRANSPORTE",
            "PASSAGEM URBANA",
        ],
    },
    VocabularyEntry {
        category_id: "apps",
        phrases: &[
            "UBER",
            "UBER TRIP",
            "99APP",
            "99 TAXI",
            "INDRIVER",
            "LADY DRIVER",
            "UBER BLACK",
            "UBER COMFORT",
            "UBER MOTO",
            "UBER FLASH",
            "UBER RESERVE",
            "99 POP",
            "99 COMFORT",
            "99 MOTO",
            "99 ENTREGA",
            "INDRIVE",
            "BLABLACAR",
            "EASY TAXI",
            "EASY TAXI APP",
            "MOBIZAP",
            "MOTORISTA 99",
            "TAXI MACHINE",
            "GO TAXI",
            "RADIO TAXI APP",
            "COOPERTAXI APP",
            "TAXI RIO APP",
            "RENTCARS",
            "LOCALIZA MEU CARRO",
            "TURBI",
            "MOOVE",
            "MOOVE CAR",
            "CARRO FACIL",
            "LOGGI",
            "LALAMOVE",
            "BORZO",
            "MOTTU",
            "MOTTU ENTREGA",
            "BUSER APP",
            "CLICKBUS APP",
            "DEONIBUS APP",
            "QUERO PASSAGEM APP",
            "BLABLACAR APP",
            "FLIXBUS",
            "FLIXBUS APP",
            "PASSARO MARRON APP",
            "ONIBUS BRASIL",
            "MOOVIT APP",
            "WAZE",
            "IFOOD APP",
            "RAPPI APP",
            "DELIVERY MUCH APP",
            "KEETA APP",
            "UBER DIRECT",
            "UBER LOGISTICS",
            "UBER TRANSIT",
            "99 ENTREGA APP",
            "99 MOTO APP",
            "MOTTU APP",
            "TURBI APP",
            "KOVI APP",
            "TEMBICI",
            "BIKE ITAU",
            "SCOO",
            "CITTAMOBI APP",
            "QUICKO APP",
            "CORRIDA DE APLICATIVO",
            "MOTORISTA DE APLICATIVO",
            "MOBILIDADE POR APLICATIVO",
        ],
    },
    VocabularyEntry {
        category_id: "transport",
        phrases: &[
            "SEM PARAR",
            "CONECTCAR",
            "VELOE",
            "ESTAPAR",
            "ZUL DIGITAL",
            "ESTACIONAMENTO",
            "PEDAGIO",
            "OFICINA MECANICA",
            "AUTO PECAS",
            "BORRACHARIA",
            "PORTO SEGURO AUTO",
            "AUTOPASS",
            "VIA FACIL",
            "VIA EXPRESSA",
            "MOVE MAIS",
            "TAGGY",
            "TAG VELOE",
            "TAG CONECTCAR",
            "TAG SEM PARAR",
            "TAG AUTOPASS",
            "DRIVE ON",
            "ZUL PARK",
            "DIGIPARE",
            "VAGA INTELIGENTE",
            "ESTACIONA RIO",
            "ESTACIONAMENTO ROTATIVO",
            "ESTACIONAMENTO DIGITAL",
            "ESTACIONAMENTO SHOPPING",
            "PARKING PAY",
            "INDIGO PARK",
            "ESTAPAR PARK",
            "MULTIPARK",
            "PARKING VAGA",
            "PARKING CENTER",
            "PARE BEM",
            "AUTO SHOPPING",
            "AUTO CENTER",
            "D PASCHOAL",
            "DPASCHOAL",
            "CAOA",
            "CAOA CHERY",
            "LOCALIZA SEMINOVOS",
            "UNIDAS SEMINOVOS",
            "MOVIDA SEMINOVOS",
            "AUTOMOB",
            "CAMPNEUS",
            "PIRELLI",
            "GOODYEAR",
            "MICHELIN",
            "BRIDGESTONE",
            "FIRESTONE",
            "CONTINENTAL PNEUS",
            "DUNLOP",
            "PNEUSTORE",
            "JAC MOTORS",
            "MERCEDES BENZ",
            "VOLKSWAGEN",
            "CHEVROLET",
            "FIAT",
            "FORD",
            "TOYOTA",
            "HONDA MOTOS",
            "YAMAHA MOTOS",
            "RENAULT",
            "NISSAN",
            "HYUNDAI",
            "JEEP",
            "PEUGEOT",
            "CITROEN",
            "MITSUBISHI MOTORS",
            "KIA MOTORS",
            "BMW MOTORS",
            "AUDI MOTORS",
            "VOLVO CARS",
            "BYD AUTO",
            "GWM MOTORS",
            "KTM MOTOS",
            "SUZUKI MOTOS",
            "HARLEY DAVIDSON",
            "OFICINA BOSCH",
            "MECANICA EXPRESS",
            "CAR10",
            "LAVA RAPIDO",
            "LAVA CAR",
            "ESTETICA AUTOMOTIVA",
            "AUTO ELETRICA",
            "REBOQUE 24 HORAS",
            "GUINCHO",
            "DETRAN",
            "CIRETRAN",
            "ARTERIS",
            "ECO RODOVIAS",
            "CCR VIAOESTE",
            "RODOANEL",
            "VAGA CERTA",
            "CCR RODOVIAS",
            "CONCESSIONARIA RODOVIARIA",
            "REVISAO AUTOMOTIVA",
            "MANUTENCAO VEICULAR",
            "PNEUS",
        ],
    },
    VocabularyEntry {
        category_id: "utilities",
        phrases: &[
            "ENERGIA ELETRICA",
            "CEMIG",
            "COPEL",
            "ENEL",
            "LIGHT",
            "SABESP",
            "COPASA",
            "SANEAMENTO",
            "EQUATORIAL ENERGIA",
            "ENERGISA",
            "CELESC",
            "CPFL ENERGIA",
            "NEOENERGIA",
            "COELBA",
            "CELPE",
            "COSERN",
            "CAGECE",
            "CEDAE",
            "SANEPAR",
            "CORSAN",
            "COMGAS",
            "COMPAGAS",
            "GAS NATURAL",
            "CONTA DE AGUA",
            "CONTA DE LUZ",
            "ENERGISA TOCANTINS",
            "ENERGISA MINAS",
            "ENERGISA SUL SUDESTE",
            "ENERGISA PARAIBA",
            "ENERGISA SERGIPE",
            "ENERGISA MATO GROSSO",
            "ENERGISA RONDONIA",
            "EQUATORIAL MARANHAO",
            "EQUATORIAL PARA",
            "EQUATORIAL PIAUI",
            "EQUATORIAL GOIAS",
            "EQUATORIAL RIO GRANDE DO SUL",
            "NEOENERGIA BRASILIA",
            "NEOENERGIA PERNAMBUCO",
            "NEOENERGIA COELBA",
            "NEOENERGIA COSERN",
            "NEOENERGIA ELEKTRO",
            "EDP SAO PAULO",
            "EDP ESPIRITO SANTO",
            "CPFL PAULISTA",
            "CPFL PIRATININGA",
            "CPFL SANTA CRUZ",
            "RGE SUL",
            "ELEKTRO",
            "CFL ENERGIA",
            "ENEL SAO PAULO",
            "ENEL RIO",
            "ENEL CEARA",
            "ENEL GOIAS",
            "COPEL DISTRIBUICAO",
            "COPEL PARANA",
            "CEMIG DISTRIBUICAO",
            "CEMIG GAS",
            "ESELETROPAULO",
            "LIGHT SERVICOS",
            "LIGHT SESA",
            "CELESC DISTRIBUICAO",
            "CELESC GERACAO",
            "ENERGIA AMAZONAS",
            "RORAIMA ENERGIA",
            "EDP BRASIL",
            "CEAL",
            "CELG",
            "CERON",
            "CERR",
            "BOA VISTA ENERGIA",
            "COSERN ENERGIA",
            "CELG D",
            "CELPA",
            "SAELPA",
            "CEAL DISTRIBUICAO",
            "CEMAR",
            "CEMAT",
            "CEEE",
            "CEEE EQUATORIAL",
            "AES BRASIL",
            "AES TIETE",
            "ENGIE BRASIL",
            "CTEEP",
            "CORSAN AGUA",
            "SABESP AGUA",
            "SABESP ESGOTO",
            "SANEPAR AGUA",
            "SANEPAR ESGOTO",
            "COPASA AGUA",
            "COPASA MG",
            "CAESB",
            "CAERN",
            "CAGEPA",
            "CASAL AGUA",
            "CASAN",
            "CEDAE AGUA",
            "DESO",
            "DESO SERGIPE",
            "EMBASA",
            "COMPESA",
            "CAGECE AGUA",
            "SAAE",
            "SANASA",
            "DAE JUNDIAI",
            "DAE BAURU",
            "DMAE PORTO ALEGRE",
            "DMAE UBERLANDIA",
            "SAMAE",
            "AGUAS DO RIO",
            "IGUAS",
            "BRK AMBIENTAL",
            "GS INIMA",
            "IGUASSSU SANEAMENTO",
            "COMGAS GAS",
            "SULGAS",
            "COMPAGAS GAS",
            "GASMIG",
            "NACIONAL GAS",
            "ULTRAGAZ",
            "LIQUIGAS",
            "COPAGAZ",
            "SUPERGASBRAS",
            "FOGAS",
            "MORRINHOS GAS",
            "GAS BRASILIANO",
            "GAS NATURAL FENOSA",
            "CONTA DE ENERGIA",
            "CONTA DE AGUA E ESGOTO",
            "CONTA DE GAS",
            "DISTRIBUIDORA DE ENERGIA",
            "SERVICO DE SANEAMENTO",
            "FORNECIMENTO DE GAS",
        ],
    },
    VocabularyEntry {
        category_id: "bills",
        phrases: &[
            "INTERNET",
            "BANDA LARGA",
            "PROVEDOR DE INTERNET",
            "CLARO NET",
            "NET VIRTUA",
            "VIVO FIBRA",
            "OI FIBRA",
            "TIM ULTRAFIBRA",
            "ALGAR TELECOM",
            "TELEFONIA",
            "CONTA DE TELEFONE",
            "FATURA DE TELEFONE",
            "PLANO CELULAR",
            "RECARGA CELULAR",
        ],
    },
    VocabularyEntry {
        category_id: "rent",
        phrases: &[
            "ALUGUEL RESIDENCIAL",
            "PAGAMENTO ALUGUEL",
            "TAXA CONDOMINIAL",
            "CONDOMINIO RESIDENCIAL",
            "QUINTOANDAR ALUGUEL",
            "LOFT ALUGUEL",
            "QUINTO ANDAR",
            "QUINTOANDAR",
            "VIVA REAL",
            "ZAP IMOVEIS",
            "OLX IMOVEIS",
            "IMOVELWEB",
            "CHAVES NA MAO",
            "WIMOVEIS",
            "NETIMOVEIS",
            "AUXILIADORA PREDIAL",
            "LOPES IMOVEIS",
            "LOPES",
            "COELHO DA FONSECA",
            "NOVA RIO IMOVEIS",
            "BRASIL BROKERS",
            "LUGAR CERTO",
            "CASA MINEIRA",
            "REDE MORAR",
            "MORAR BEM",
            "CREDPAGO",
            "ALUGUEL DIGITAL",
            "HUBERT IMOVEIS",
            "LOCARE",
            "HUGO IMOVEIS",
            "APTO",
            "HOUSES",
            "AIRBNB",
            "BOOKING ALUGUEL",
            "VRBO",
            "FLAT",
            "STUDIO RESIDENCE",
            "HOSPEDAGEM RESIDENCIAL",
            "CONDOMINIO",
            "CONDOMINIO ONLINE",
            "CONDOMINIO DIGITAL",
            "SINDICO NET",
            "SUPERLOGICA CONDOMINIOS",
            "TOWN SQ",
            "MYVILLAGE",
            "AHREND",
            "ADMINISTRADORA DE CONDOMINIO",
            "TAXA EXTRA CONDOMINIO",
            "FUNDO DE RESERVA",
            "SEGURO FIANCA",
            "FIADOR",
            "DEPOSITO CAUCAO",
            "GARANTIA ALUGUEL",
            "TAXA DE ADMINISTRACAO IMOBILIARIA",
            "HONORARIOS IMOBILIARIOS",
            "PAGAMENTO LOCACAO",
            "LOCACAO RESIDENCIAL",
            "ALUGUEL COMERCIAL",
            "ALUGUEL SALA",
            "ALUGUEL BOX",
            "ALUGUEL GARAGEM",
            "PREDIAL",
            "PORTARIA REMOTA",
            "SEGURANCA CONDOMINIAL",
            "LIMPEZA CONDOMINIAL",
            "VIVAREAL ALUGUEL",
            "ZAP IMOVEIS ALUGUEL",
            "IMOVELWEB ALUGUEL",
            "OLX IMOVEIS ALUGUEL",
            "REMAX BRASIL",
            "VIVA REAL IMOVEIS",
            "ZAP IMOVEIS BRASIL",
            "IMOVELWEB BRASIL",
            "LOFT IMOVEIS",
            "QUINTO ANDAR IMOVEIS",
            "HABITACIONAL",
            "CREDPAGO ALUGUEL",
            "ALUGUEL GARANTIDO",
            "TOKIO MARINE ALUGUEL",
            "PORTO ALUGUEL",
            "POTTENCIAL",
            "SEGURO FIANCA PORTO",
            "SEGURO FIANCA TOKIO",
            "ADMINISTRADORA LELLO",
            "LUIZ CARLOS CONDOMINIOS",
            "BRCONDOS",
            "CONDOMINIO21",
            "BASE SOFTWARE CONDOMINIO",
            "AHREND CONDOMINIOS",
            "LOCARE IMOVEIS",
            "ALUGAQUI",
            "ALUGUEL DE IMOVEL",
            "PAGAMENTO DE LOCACAO",
            "TAXA DE CONDOMINIO",
            "FUNDO DE OBRAS CONDOMINIO",
            "MUDANCA RESIDENCIAL",
            "ALUGUEL TEMPORADA",
            "ALUGUEL KITNET",
            "ALUGUEL APARTAMENTO",
            "ALUGUEL CASA",
            "ALUGUEL",
            "LOCACAO",
            "CONDOMINIO MENSAL",
            "ADMINISTRADORA DE IMOVEIS",
            "IMOBILIARIA",
        ],
    },
    VocabularyEntry {
        category_id: "housing",
        phrases: &[
            "LEROY MERLIN",
            "TELHANORTE",
            "C C CASA CONSTRUCAO",
            "MATERIAL DE CONSTRUCAO",
            "TOK STOK",
            "LEROY MERLIN BRASIL",
            "TELHANORTE BRASIL",
            "TUMELERO",
            "DICICO",
            "JOLI",
            "CASSOL",
            "BENOIT",
            "CONSTRUMART",
            "OBRAMAX",
            "MATERIAL DE CONSTRUCAO LEROY",
            "C C",
            "TIGRE",
            "CORAL TINTAS",
            "SUVINIL",
            "SHERWIN WILLIAMS",
            "LUKSCOLOR",
            "SUVINIL TINTAS",
            "DURATEX",
            "EUCATEX",
            "PORTOBELLO",
            "ELIANE REVESTIMENTOS",
            "CEUSA",
            "INCEPA",
            "ROCA",
            "DECA",
            "DOCOL",
            "CELITE",
            "TRAMONTINA",
            "STOLF",
            "LIGAFORT",
            "SCA",
            "FINGER MOVEIS",
            "PLANEJADOS",
            "CASA E VIDEO",
            "CAMICADO CASA",
            "ETNA",
            "MOBLY CASA",
            "MADEIRA MADEIRA MOVEIS",
            "ORIGAMI MOVEIS",
            "TOK STOK CASA",
            "LEROY JARDIM",
            "COBASI CASA",
            "PETZ CASA",
            "LEROY FERRAMENTAS",
            "STANLEY FERRAMENTAS",
            "DEWALT",
            "BOSCH FERRAMENTAS",
            "MAKITA",
            "VONDER",
            "IRWIN",
            "BLACK DECKER",
            "3M CONSTRUCAO",
            "WAP",
            "KARCHER",
            "PHILIPS WALITA",
            "MONDIAL ELETRO",
            "BRITANIA",
            "CADENCE",
            "OSTER",
            "ELECTROLUX",
            "BRASTEMP",
            "CONSUL",
            "MIDEA",
            "SUGGAR",
            "PANASONIC CASA",
            "SAMSUNG CASA",
            "LG CASA",
            "ARNO",
            "MALLORY",
            "NARDI",
            "FISCHER",
            "FOGATTI",
            "ITATIAIA",
            "TAPECARIA",
            "LEROY PISOS",
            "REVESTIR",
            "DICICO TINTAS",
            "CASA SHOW",
            "CASA E CIA",
            "CONSTRUFORTE",
            "TUDO PARA CONSTRUCAO",
            "CASA DAS TINTAS",
            "REI DAS TINTAS",
            "TELHANORTE TINTAS",
            "CASSOL CENTERLAR",
            "QUERO QUERO CONSTRUCAO",
            "TODIMO MATERIAIS",
            "DICICO CONSTRUCAO",
            "CONSTRUDECOR",
            "CASA EUROPA MOVEIS",
            "ORTOBOM",
            "FERREIRA COSTA",
            "SODIMAC BRASIL",
            "COLCHOES CASTOR",
            "COLCHOES PROBEL",
            "LOJA DE MOVEIS",
            "MOVEIS PLANEJADOS",
            "MATERIAL ELETRICO",
            "MATERIAL HIDRAULICO",
            "FERRAGISTA",
            "LOJA DE TINTAS",
            "ELETRODOMESTICOS",
        ],
    },
    VocabularyEntry {
        category_id: "health",
        phrases: &[
            "FARMACIA",
            "DROGARIA",
            "HOSPITAL",
            "CLINICA MEDICA",
            "CLINICA ODONTOLOGICA",
            "LABORATORIO CLINICO",
            "DROGASIL",
            "DROGA RAIA",
            "PACHECO DROGARIAS",
            "DROGARIA SAO PAULO",
            "PAGUE MENOS",
            "PANVEL",
            "ULTRAFARMA",
            "NISSEI FARMACIAS",
            "EXAME LABORATORIAL",
            "CONSULTA MEDICA",
            "CONSULTA ODONTOLOGICA",
            "PLANO DE SAUDE",
            "UNIMED",
            "AMIL SAUDE",
            "HAPVIDA",
            "ODONTOPREV",
            "DASA",
            "FLEURY MEDICINA",
            "CLAMED",
            "DROGAL",
            "FARMACIA INDIANA",
            "DROGARIA VENANCIO",
            "REDE D1000",
            "FARMA CONDE",
            "FARMAIS",
            "REDEPHARMA",
            "DROGARIAS GLOBO",
            "FARMACIA PERMANENTE",
            "GRUPO TAPAJOS",
            "EXTRAFARMA",
            "BIG BEN",
            "DORFARMA",
            "DROGARIA CATARINENSE",
            "FARMACIA PRECO POPULAR",
            "DROGARIA MODERNA",
            "DROGARIA POUPE MAIS",
            "DROGARIA TOTAL",
            "DROGARIA MINAS BRASIL",
            "FARMELHOR",
            "FARMACIA DO TRABALHADOR",
            "FARMACIA POPULAR",
            "DASA DIAGNOSTICOS",
            "HOSPITAL ALBERT EINSTEIN",
            "SIRIO LIBANES",
            "REDE DOR",
            "NOTREDAME INTERMEDICA",
            "BRADESCO SAUDE",
            "SULAMERICA SAUDE",
            "PORTO SAUDE",
            "SAMI SAUDE",
            "ALICE SAUDE",
            "PREVENT SENIOR",
            "OMINT SAUDE",
            "CARE PLUS SAUDE",
            "GOLDEN CROSS SAUDE",
            "BIOVIDA SAUDE",
            "MEDSENIOR",
            "HOSPITAL OSWALDO CRUZ",
            "HOSPITAL MOINHOS DE VENTO",
            "HOSPITAL MADRE TERESA",
            "HOSPITAL SAMARITANO",
            "HOSPITAL PAULISTA",
            "HOSPITAL VILLA LOBOS",
            "HOSPITAL BANDEIRANTES",
            "HOSPITAL AC CAMARGO",
            "HOSPITAL PEQUENO PRINCIPE",
            "HOSPITAL DAS CLINICAS",
            "HOSPITAL SANTA CATARINA",
            "HOSPITAL PORTUGUES",
            "HOSPITAL VERA CRUZ",
            "HOSPITAL SAO LUIZ",
            "LABORATORIO FLEURY",
            "DELBONI AURIEMO",
            "LAVOISIER",
            "SALOMAO ZOPPI",
            "HERMES PARDINI",
            "SABIN DIAGNOSTICO",
            "BRONSTEIN",
            "DB MOLECULAR",
            "VITAL BRASIL",
            "CLINICA AMO",
            "ODONTOCOMPANY",
            "ORAL SIN",
            "DR CONSULTA",
            "CLINICA SIM",
            "CLINICA FARES",
            "PSICOLOGIA VIVA",
            "ZENKLUB",
            "CONVIVERE SAUDE",
            "NEO QUIMICA",
            "ACHE LABORATORIOS",
            "EUROFARMA",
            "EMS",
            "HYPERA PHARMA",
            "TEUTO",
            "MEDLEY",
            "BAYER SAUDE",
            "PFIZER SAUDE",
            "ROCHE DIAGNOSTICA",
            "NOVARTIS",
            "SANOFI",
            "JOHNSON JOHNSON SAUDE",
            "ABBOTT",
            "TAKEDA",
            "ASTRAZENECA",
            "MERCK SAUDE",
            "GSK SAUDE",
            "ELI LILLY",
            "PAGUE MENOS LOJA",
            "DROGARIA PAGUE MENOS",
            "RD SAUDE",
            "DPSP",
            "FARMACIA SAO JOAO",
            "DROGARIA ARAUJO",
            "CLINICA",
            "LABORATORIO",
            "CONSULTORIO MEDICO",
            "CONSULTORIO ODONTOLOGICO",
            "PRONTO SOCORRO",
            "CENTRO MEDICO",
        ],
    },
    VocabularyEntry {
        category_id: "education",
        phrases: &[
            "MENSALIDADE ESCOLAR",
            "MENSALIDADE FACULDADE",
            "MENSALIDADE UNIVERSIDADE",
            "ESCOLA DE IDIOMAS",
            "CURSO ONLINE",
            "CURSO PROFISSIONALIZANTE",
            "COLEGIO",
            "FACULDADE",
            "UNIVERSIDADE",
            "ALURA",
            "UDEMY",
            "COURSERA",
            "DUOLINGO",
            "ROCKETSEAT",
            "DESCOMPLICA",
            "CULTURA INGLESA",
            "WIZARD IDIOMAS",
            "CCAA IDIOMAS",
            "LIVRARIA SARAIVA",
            "KULTIVI",
            "DIO",
            "TRYBE",
            "EBAC",
            "PM3",
            "CUBOS ACADEMY",
            "GAMA ACADEMY",
            "FIAP",
            "DIGITAL HOUSE",
            "HASHTAG TREINAMENTOS",
            "GRAN CURSOS",
            "ESTRATEGIA CONCURSOS",
            "ESTRATEGIA VESTIBULARES",
            "DAMASIO",
            "FOCUS CONCURSOS",
            "ALFACON",
            "CERS",
            "QCONCURSOS",
            "TEC CONCURSOS",
            "APROVA CONCURSOS",
            "ME SALVA",
            "STOODI",
            "KUADRO",
            "BIOLIO",
            "DESCOMPLICA VESTIBULAR",
            "ANGLO",
            "POLIEDRO",
            "OBJETIVO",
            "ETAPA",
            "FARIAS BRITO",
            "COLEGIO DANTE ALIGHIERI",
            "BANDEIRANTES COLEGIO",
            "MARISTA",
            "SALESIANO",
            "DOM BOSCO COLEGIO",
            "POSITIVO COLEGIO",
            "COC SISTEMA",
            "PENSI",
            "PHD COLEGIO",
            "ELEVA EDUCACAO",
            "PIO XII",
            "SANTA MARCELINA",
            "MAPLE BEAR",
            "RED HOUSE",
            "KUMON",
            "WIZARD",
            "CCAA",
            "YAZIGI",
            "FISK",
            "CNA IDIOMAS",
            "BRITANNIA ESCOLA",
            "OXFORD IDIOMAS",
            "CAMBRIDGE IDIOMAS",
            "BERLITZ",
            "INFLUX",
            "ROCKFELLER LANGUAGE",
            "NUMBER ONE IDIOMAS",
            "WISE UP",
            "OPEN ENGLISH",
            "ENGLISH LIVE",
            "CAMBLY",
            "ITALKI",
            "SENAC",
            "SENAI",
            "SESI EDUCACAO",
            "SEBRAE CURSOS",
            "SESC EDUCACAO",
            "ESCOLA DA NUVEM",
            "USP",
            "UNICAMP",
            "UNESP",
            "UFRJ",
            "UFMG",
            "UFPR",
            "UFRGS",
            "UNB",
            "UFSC",
            "PUC SP",
            "PUC RIO",
            "PUC MINAS",
            "MACKENZIE",
            "FGV",
            "INSPER",
            "IBMEC",
            "ESTACIO",
            "ANHANGUERA",
            "UNIP",
            "UNINOVE",
            "UNINTER",
            "CRUZEIRO DO SUL",
            "UNISINOS",
            "UNIVALI",
            "UNICESUMAR",
            "UNIASSELVI",
            "UNIVERSIDADE POSITIVO",
            "UNIFESP",
            "UERJ",
            "PASSEI DIRETO",
            "ESCOLA",
            "CURSO",
            "CURSINHO",
            "MATERIAL ESCOLAR",
            "LIVRARIA",
            "IDIOMAS",
            "POS GRADUACAO",
        ],
    },
    VocabularyEntry {
        category_id: "personal-care",
        phrases: &[
            "SALAO DE BELEZA",
            "BARBEARIA",
            "MANICURE",
            "PEDICURE",
            "DEPILACAO",
            "ESTETICA FACIAL",
            "ESTETICA CORPORAL",
            "COSMETICOS",
            "PERFUMARIA",
            "O BOTICARIO",
            "NATURA COSMETICOS",
            "SEPHORA",
            "BEAUTYBOX",
            "EUDORA",
            "QUEM DISSE BERENICE",
            "VULT COSMETICOS",
            "DAILUS",
            "IMPALA ESMALTES",
            "RISQUE ESMALTES",
            "COLORAMA",
            "OPI ESMALTES",
            "SALLYS",
            "IKESAKI",
            "BELEZA NA WEB",
            "EPOCA COSMETICOS",
            "BRAE",
            "WELLA",
            "LOREAL",
            "KERASTASE",
            "REDKEN",
            "SCHWARZKOPF",
            "PANTENE",
            "HEAD SHOULDERS",
            "DOVE",
            "NIVEA",
            "NEUTROGENA",
            "CERAVE",
            "LA ROCHE POSAY",
            "VICHY",
            "ADCOS",
            "BIODERMA",
            "ESMALTERIA NACIONAL",
            "SPA DAS SOBRANCELHAS",
            "ESPACOLASER",
            "DEPILARTE",
            "LASER FAST",
            "GIOLASER",
            "JACQUES JANINE",
            "SOHO HAIR",
            "WERNER COIFFEUR",
            "CELSO KAMURA",
            "STUDIO W",
            "BEAUTY HAIR",
            "SUMIRE",
            "ROMA CABELEIREIROS",
            "FAST ESCOVA",
            "MULHER CHEIROSA",
            "MR FRISE",
            "BARBEARIA VIP",
            "DON ALCIDES",
            "BARBEARIA DOM HENRIQUE",
            "BARBEARIA TRAJANO",
            "BARBEARIA FIORENTINA",
            "BARBEARIA IMPERIAL",
            "UNHAS CARIOCAS",
            "DERMAGE",
            "BOTOCENTER",
            "HINODE",
            "JEQUITI",
            "MARY KAY",
            "HERBALIFE",
            "YVES ROCHER",
            "KIKO MILANO",
            "REVLON",
            "MAYBELLINE",
            "NYX COSMETICS",
            "URBAN DECAY",
            "BENEFIT COSMETICS",
            "NARS COSMETICS",
            "DIOR BEAUTY",
            "CHANEL BEAUTY",
            "ESTEE LAUDER",
            "SHISEIDO",
            "THE BODY SHOP",
            "LUSH COSMETICOS",
            "SABON COSMETICOS",
            "AMARO BEAUTY",
            "BRAE COSMETICOS",
            "KABENI COSMETICOS",
            "OCEANE",
            "SALLVE",
            "SIMPLE ORGANIC",
            "BIOSSANCE",
            "SKEYNDOR",
            "PAYOT",
            "DERMAGE COSMETICOS",
            "ADCOS DERMOCOSMETICOS",
            "CLINIQUE",
            "ELSEVE",
            "TRESEMME",
            "CLEAR",
            "SENSODYNE",
            "COLGATE",
            "ORAL B",
            "CREST",
            "DEPILACAO A LASER",
            "SPA URBANO",
            "MASSAGEM RELAXANTE",
            "MANICURE E PEDICURE",
            "LOJAS REDE",
            "GRUPO BOTICARIO",
            "NATURA",
            "AVON",
            "SALAO",
            "CENTRO DE ESTETICA",
            "CLINICA DE ESTETICA",
            "CABELEIREIRO",
            "ESMALTERIA",
        ],
    },
    VocabularyEntry {
        category_id: "insurance",
        phrases: &[
            "SEGURADORA",
            "SEGURO AUTO",
            "SEGURO VIDA",
            "SEGURO RESIDENCIAL",
            "SEGURO PRESTAMISTA",
            "PREMIO DE SEGURO",
            "PORTO SEGURO CIA SEGUROS",
            "AZUL SEGUROS",
            "TOKIO MARINE SEGURADORA",
            "MAPFRE SEGUROS",
            "HDI SEGUROS",
            "ALLIANZ SEGUROS",
            "ZURICH SEGUROS",
            "SULAMERICA SEGUROS",
            "BRADESCO SEGUROS",
            "LIBERTY SEGUROS",
            "PORTO SEGURO",
            "PORTO SEGUROS",
            "ITAU SEGUROS",
            "ITAU VIDA E PREVIDENCIA",
            "BRADESCO VIDA E PREVIDENCIA",
            "SANTANDER AUTO",
            "SANTANDER SEGUROS",
            "SANTANDER CAPITALIZACAO",
            "TOKIO MARINE",
            "TOKIO MARINE SEGUROS",
            "CHUBB SEGUROS",
            "SOMPO SEGUROS",
            "PRUDENTIAL SEGUROS",
            "METLIFE SEGUROS",
            "ICATU SEGUROS",
            "MAG SEGUROS",
            "GENERALI SEGUROS",
            "YASUDA SEGUROS",
            "SANCOR SEGUROS",
            "CAIXA SEGURIDADE",
            "CAIXA SEGUROS",
            "CAIXA VIDA E PREVIDENCIA",
            "BB SEGUROS",
            "BRASILPREV",
            "BRASILPREV SEGUROS",
            "RODOBENS SEGUROS",
            "YOUSE SEGUROS",
            "JUSTOS SEGUROS",
            "PIER SEGUROS",
            "180 SEGUROS",
            "88I SEGURADORA",
            "NEOS SEGUROS",
            "NEON SEGUROS",
            "LTI SEGUROS",
            "JNS SEGURADORA",
            "SAFRA SEGUROS",
            "SAFRA VIDA",
            "ALFA SEGUROS",
            "ALFA PREVIDENCIA",
            "ESSOR SEGUROS",
            "ARGO SEGUROS",
            "BERKLEY SEGUROS",
            "ESSENCIAL SEGUROS",
            "PREVISUL SEGUROS",
            "MBM SEGUROS",
            "NOBRE SEGUROS",
            "SURA SEGUROS",
            "TUDO SEGUROS",
            "SURA CORPORATE",
            "CAPEMISA SEGUROS",
            "MONGERAL AEGON",
            "MONGERAL SEGUROS",
            "MAGALHAES SEGUROS",
            "BANCO DO BRASIL SEGUROS",
            "SICREDI SEGUROS",
            "SICOOB SEGUROS",
            "UNIMED SEGUROS",
            "ODONTOPREV SEGUROS",
            "DENTAL UNI",
            "METLIFE ODONTO",
            "CAIXA CAPITALIZACAO",
            "ICATU CAPITALIZACAO",
            "BRADESCO CAPITALIZACAO",
            "PORTO CAPITALIZACAO",
            "SANTANDER PREVIDENCIA",
            "BRADESCO PREVIDENCIA",
            "ITAU PREVIDENCIA",
            "XP SEGUROS",
            "RICO SEGUROS",
            "BTG SEGUROS",
            "INTER SEGUROS",
            "MITSUI SUMITOMO",
            "MITSUI SEGUROS",
            "AKAD SEGUROS",
            "BMG SEGUROS",
            "BANCO PAN SEGUROS",
            "C6 SEGUROS",
            "NUBANK CELULAR SEGURO",
            "PAGBANK SEGUROS",
            "MASSA SEGURADORA",
            "KOVI SEGURO",
            "LOOVI SEGUROS",
            "PIER CELULAR",
            "LOOVI PROTECAO",
            "PROTEGE AUTO",
            "APVS BRASIL",
            "COBERTURA FACIL",
            "SEGURO DESEMPREGO",
            "SEGURO VIAGEM",
            "SEGURO CELULAR",
            "SEGURO PET",
            "SEGURO BIKE",
            "SEGURO",
            "CORRETORA DE SEGUROS",
            "PROTECAO VEICULAR",
            "APOLICE",
        ],
    },
    VocabularyEntry {
        category_id: "bank-fees",
        phrases: &[
            "TARIFA BANCARIA",
            "PACOTE DE SERVICOS",
            "PACOTE SERVICOS",
            "CESTA DE SERVICOS",
            "TARIFA MANUTENCAO",
            "TARIFA SAQUE",
            "TARIFA PIX",
            "TARIFA TED",
            "TARIFA DOC",
            "ANUIDADE CARTAO",
            "JUROS ROTATIVO",
            "ENCARGOS FINANCEIROS",
        ],
    },
    VocabularyEntry {
        category_id: "taxes",
        phrases: &[
            "IPTU",
            "IPVA",
            "DARF",
            "DAS SIMPLES NACIONAL",
            "GUIA DAS MEI",
            "GPS INSS",
            "GUIA INSS",
            "IMPOSTO DE RENDA",
            "RECEITA FEDERAL",
            "SECRETARIA DA FAZENDA",
            "SEFAZ",
            "TAXA LICENCIAMENTO",
            "LICENCIAMENTO VEICULO",
            "ISSQN",
            "ITBI",
            "ITCMD",
        ],
    },
    VocabularyEntry {
        category_id: "investments",
        phrases: &[
            "TESOURO DIRETO",
            "APLICACAO FINANCEIRA",
            "APLICACAO CDB",
            "APLICACAO LCI",
            "APLICACAO LCA",
            "COMPRA DE ACOES",
            "FUNDO DE INVESTIMENTO",
            "PREVIDENCIA PRIVADA",
            "XP INVESTIMENTOS",
            "RICO INVESTIMENTOS",
            "CLEAR CORRETORA",
            "BTG PACTUAL CORRETORA",
            "GENIAL INVESTIMENTOS",
            "NUINVEST",
            "ORAMA INVESTIMENTOS",
            "TORO INVESTIMENTOS",
            "AVENUE SECURITIES",
            "INTER INVEST",
            "MODALMAIS",
            "B3 INVESTIDOR",
        ],
    },
    VocabularyEntry {
        category_id: "salary",
        phrases: &[
            "SALARIO",
            "PAGAMENTO DE SALARIO",
            "CREDITO SALARIO",
            "PAGAMENTO FOLHA",
            "CREDITO FOLHA",
            "ADIANTAMENTO SALARIAL",
            "DECIMO TERCEIRO SALARIO",
            "FERIAS PAGAMENTO",
        ],
    },
    VocabularyEntry {
        category_id: "other-income",
        phrases: &[
            "RESTITUICAO IMPOSTO DE RENDA",
            "RESTITUICAO IRPF",
            "DISTRIBUICAO DE LUCROS",
            "PAGAMENTO DIVIDENDOS",
            "JUROS SOBRE CAPITAL PROPRIO",
        ],
    },
    VocabularyEntry {
        category_id: "other-expenses",
        phrases: &[
            "OUTRAS DESPESAS",
            "DESPESA DIVERSA",
            "DESPESAS DIVERSAS",
            "GASTOS DIVERSOS",
            "DOACAO",
            "CONTRIBUICAO BENEFICENTE",
            "AJUDA FINANCEIRA",
        ],
    },
    VocabularyEntry {
        category_id: "leisure",
        phrases: &[
            "INGRESSO COM",
            "CINEMARK",
            "CINEPOLIS",
            "UCI CINEMAS",
            "SYMPLA",
            "TICKETMASTER BRASIL",
            "STEAM GAMES",
            "PLAYSTATION NETWORK",
            "NINTENDO ESHOP",
            "XBOX GAME PASS",
            "PARQUE DE DIVERSOES",
            "TEATRO INGRESSO",
            "INGRESSO RAPIDO",
            "EVENTIM BRASIL",
            "STEAM STORE",
            "EPIC GAMES STORE",
            "PLAYSTATION STORE",
            "NINTENDO STORE",
            "RIOT GAMES",
            "BLIZZARD ENTERTAINMENT",
            "GOG COM",
            "HUMBLE BUNDLE",
            "POKEMON GO",
            "ROBLOX",
            "MINECRAFT",
            "FORTNITE",
            "CLASH ROYALE",
            "ARENA OF VALOR",
            "DISCORD NITRO",
            "TWITCH SUBS",
            "TICKET SPORTS",
            "PREMIERE FUTEBOL",
            "COMBATE UFC",
            "NBA LEAGUE PASS",
            "NFL GAME PASS",
            "F1 TV",
            "ESPN APP",
            "GLOBO ESPORTE",
            "PARQUE IBIRAPUERA",
            "BETO CARRERO WORLD",
            "HOPI HARI",
            "THERMAS DOS LARANJAIS",
            "HOT PARK",
            "WET N WILD",
            "PARQUE DA MONICA",
            "AQUARIO DE SAO PAULO",
            "ZOO SAO PAULO",
            "JARDIM BOTANICO",
            "MUSEU DO FUTEBOL",
            "MASP",
            "CCBB",
            "MUSEU DO AMANHA",
            "INHOTIM",
            "BIENAL DE SAO PAULO",
            "SESC CULTURA",
            "ITAUCULTURA",
            "MIS SP",
            "OSB ORQUESTRA",
            "THEATRO MUNICIPAL",
            "TEATRO RENAULT",
            "TEATRO ALFA",
            "TEATRO BRADESCO",
            "CASA DE CULTURA",
            "CVC BRASIL",
            "DECOLAR",
            "HURB",
            "123MILHAS",
            "LATAM TRAVEL",
            "AZUL VIAGENS",
            "GOL VIAGENS",
            "HOTEL URBANO",
            "HOTEL",
            "POUSADA",
            "HOSTEL",
            "BOOKING COM",
            "HOSTELWORLD",
            "TRIVAGO",
            "EXPEDIA",
            "HOTELS COM",
            "BELLA DA SERRA TURISMO",
            "AGENCIA DE VIAGENS",
            "HOTELARIA",
            "RESORT",
            "PARQUE AQUATICO",
            "BOLICHE",
            "BOLICHE VILLA",
            "ESCAPE 60",
            "PAINTBALL",
            "KART INDOOR",
            "LASER TAG",
            "PLAYCENTER",
            "BUFFET INFANTIL",
            "FESTA INFANTIL",
            "CARNAVAL INGRESSO",
            "SHOW MUSICAL",
            "FESTIVAL MUSICA",
            "LIVRO DIGITAL",
            "AUDIOLIVRO",
            "LIVRARIA CULTURA EVENTO",
            "REVISTA DIGITAL",
            "QUADRINHOS",
            "COLECIONAVEIS",
            "HOBBY",
            "PETS CAFE",
            "CLUBE DO VINHO",
            "CLUBE DE ASSINATURA",
            "ACADEMIA DE DANCA",
            "ESCOLA DE MUSICA",
            "AULA DE TEATRO",
            "AULA DE PINTURA",
            "FOTOGRAFIA CURSO",
            "CAMPING",
            "PESQUEIRO",
            "PASSEIO TURISTICO",
            "GUIA TURISTICO",
            "INGRESSO EVENTO",
            "CINEMA",
            "TEATRO",
            "MUSEU",
            "PARQUE TEMATICO",
            "CASA DE SHOWS",
            "AGENCIA DE TURISMO",
            "PASSEIO",
        ],
    },
];

#[cfg(test)]
mod tests {
    use std::collections::{HashMap, HashSet};

    use super::*;
    use crate::domain::suggestion::fold_text;

    #[test]
    fn vocabulary_is_pre_normalized_and_has_no_ambiguous_duplicate_phrases() {
        let mut categories = HashSet::new();
        let mut phrase_owner = HashMap::new();

        for entry in PT_BR_CATEGORY_VOCABULARY {
            assert!(categories.insert(entry.category_id));
            assert!(!entry.phrases.is_empty());
            for phrase in entry.phrases {
                assert_eq!(*phrase, fold_text(phrase));
                assert!(
                    phrase_owner.insert(*phrase, entry.category_id).is_none(),
                    "duplicate vocabulary phrase: {phrase}"
                );
            }
        }
    }

    #[test]
    fn vocabulary_has_broad_but_curated_local_coverage() {
        assert!(PT_BR_CATEGORY_VOCABULARY_VERSION > 0);
        let phrase_count: usize = PT_BR_CATEGORY_VOCABULARY
            .iter()
            .map(|entry| entry.phrases.len())
            .sum();
        assert!(PT_BR_CATEGORY_VOCABULARY.len() >= 20);
        assert!(phrase_count >= 200);
    }

    #[test]
    fn vocabulary_keeps_every_builtin_import_category_represented() {
        let expected: HashSet<_> = [
            "subscriptions",
            "shopping",
            "groceries",
            "restaurants",
            "fuel",
            "public-transport",
            "apps",
            "transport",
            "utilities",
            "bills",
            "rent",
            "housing",
            "health",
            "education",
            "personal-care",
            "insurance",
            "bank-fees",
            "taxes",
            "investments",
            "salary",
            "other-income",
            "other-expenses",
            "leisure",
        ]
        .into_iter()
        .collect();
        let actual: HashSet<_> = PT_BR_CATEGORY_VOCABULARY
            .iter()
            .map(|entry| entry.category_id)
            .collect();

        assert!(
            expected.is_subset(&actual),
            "missing vocabulary categories: {:?}",
            expected.difference(&actual).collect::<Vec<_>>()
        );
    }

    #[test]
    fn vocabulary_has_broad_brazilian_coverage_and_expected_genre_tags() {
        let phrase_count: usize = PT_BR_CATEGORY_VOCABULARY
            .iter()
            .map(|entry| entry.phrases.len())
            .sum();
        assert!(phrase_count >= 1_500);

        let expected_tags = [
            ("shopping", "LOJA ONLINE"),
            ("groceries", "SUPERMERCADO"),
            ("restaurants", "RESTAURANTE"),
            ("restaurants", "PADARIA"),
            ("fuel", "POSTO"),
            ("public-transport", "ONIBUS"),
            ("transport", "OFICINA MECANICA"),
            ("utilities", "CONTA DE LUZ"),
            ("bills", "INTERNET"),
            ("rent", "ALUGUEL"),
            ("housing", "MATERIAL DE CONSTRUCAO"),
            ("health", "FARMACIA"),
            ("education", "ESCOLA"),
            ("personal-care", "SALAO"),
            ("insurance", "SEGURO"),
            ("leisure", "CINEMA"),
            ("leisure", "HOTEL"),
            ("other-expenses", "OUTRAS DESPESAS"),
        ];

        for (category_id, expected_tag) in expected_tags {
            let phrases = PT_BR_CATEGORY_VOCABULARY
                .iter()
                .find(|entry| entry.category_id == category_id)
                .map(|entry| entry.phrases)
                .unwrap_or_default();
            assert!(
                phrases.contains(&expected_tag),
                "category {category_id} is missing genre tag {expected_tag}"
            );
        }
    }

    #[test]
    fn vocabulary_excludes_brands_without_relevant_operation_in_brazil() {
        let excluded = [
            "IKEA",
            "COSTCO",
            "UNIQLO",
            "FIVE GUYS",
            "WENDYS",
            "PANDA EXPRESS",
            "DIN TAI FUNG",
            "CARLS JR",
            "LYFT",
            "DIDI",
            "BEAT",
            "CABIFY",
            "ZAZCAR",
            "LIME MOBILITY",
            "YELLOW BIKE",
            "GRIN MOBILITY",
            "ESSO",
            "REPSOL",
            "GULF",
            "METRO CURITIBA",
        ];
        let phrases: HashSet<_> = PT_BR_CATEGORY_VOCABULARY
            .iter()
            .flat_map(|entry| entry.phrases.iter().copied())
            .collect();

        for brand in excluded {
            assert!(
                !phrases.contains(brand),
                "unexpected non-Brazilian brand: {brand}"
            );
        }
    }

    #[test]
    fn vocabulary_keeps_common_brazilian_merchants_from_sector_rankings() {
        let expected = [
            ("shopping", "LOJAS TORRA"),
            ("shopping", "LOJAS CEM"),
            ("groceries", "PLURIX"),
            ("groceries", "G BARBOSA"),
            ("groceries", "FORT ATACADISTA"),
            ("restaurants", "CHINA IN BOX"),
            ("restaurants", "RAGAZZO"),
            ("restaurants", "CABANA BURGER"),
            ("housing", "ORTOBOM"),
            ("health", "RD SAUDE"),
            ("health", "FARMACIA SAO JOAO"),
            ("personal-care", "GRUPO BOTICARIO"),
        ];

        for (category_id, merchant) in expected {
            let phrases = PT_BR_CATEGORY_VOCABULARY
                .iter()
                .find(|entry| entry.category_id == category_id)
                .map(|entry| entry.phrases)
                .unwrap_or_default();
            assert!(
                phrases.contains(&merchant),
                "category {category_id} is missing Brazilian merchant {merchant}"
            );
        }
    }
}
